### ISSUE TITLE
arm-image-builder wiki is unreachable 

### ISSUE THREAD

**Issue by pedro-m-ribeiro** [ptr1337/arm-img-builder-docker#7]
When I open [https://wiki.arm-image-builder.xyz/Docker](https://wiki.arm-image-builder.xyz/Docker) I get a 523 error.

![image](https://user-images.githubusercontent.com/3976564/133230581-82ff64c8-675f-47e4-a32c-ea2d3dd40557.png)

**Comment by ptr1337** [comment]
Hey, 

we canceld site. Take a watch https://github.com/pyavitz/arm-img-builder.

Should run completely perfect, if you still have questions regarding docker just hit me up

**Comment by ptr1337** [comment]
btw: 
https://github.com/ptr1337/arm-image-builder-wiki are still our old wiki stuff in :)

**Comment by pedro-m-ribeiro** [comment]
Thank you very much for the quick reply!
